DROP FUNCTION IF EXISTS WESLEYSAFADAO;
DELIMITER $$
CREATE FUNCTION WESLEYSAFADAO(DDAY INT, MMONTH INT, YYEAR INT) RETURNS VARCHAR(60) DETERMINISTIC
BEGIN
  DECLARE MYSUM, SAFADEZA, ANJO DOUBLE;
  SET MYSUM = 0;
  SET SAFADEZA = 0;
  SET ANJO = 0;
  WHILE MMONTH > 0 DO
    SET MYSUM = MYSUM + MMONTH;
    SET MMONTH = MMONTH - 1;
  END WHILE;
  SET SAFADEZA = MYSUM + (YYEAR / 100) * (50 - DDAY);
  SET ANJO = 100 - SAFADEZA;
  RETURN CONCAT("Você é ", ROUND(SAFADEZA, 2), "% safado e ", ROUND(ANJO, 2), "% anjo");
END
$$
SELECT WESLEYSAFADAO(5, 9, 91);

